package io.github.masyumero.mekanismmorecapacity.common.config;

import mekanism.common.config.BaseMekanismConfig;
import mekanism.common.config.value.CachedIntValue;
import mekanism.common.config.value.CachedLongValue;
import net.minecraftforge.common.ForgeConfigSpec;
import net.minecraftforge.fml.config.ModConfig;

public class MMCMekExtrasMachineConfig extends BaseMekanismConfig {

    private final ForgeConfigSpec configSpec;
    public final CachedLongValue AbsoluteMetallurgicInfuserFactory;
    public final CachedLongValue SupremeMetallurgicInfuserFactory;
    public final CachedLongValue CosmicMetallurgicInfuserFactory;
    public final CachedLongValue InfiniteMetallurgicInfuserFactory;
    public final CachedLongValue AbsoluteCompressing;
    public final CachedLongValue SupremeCompressing;
    public final CachedLongValue CosmicCompressing;
    public final CachedLongValue InfiniteCompressing;
    public final CachedLongValue AbsoluteInjecting;
    public final CachedLongValue SupremeInjecting;
    public final CachedLongValue CosmicInjecting;
    public final CachedLongValue InfiniteInjecting;
    public final CachedLongValue AbsolutePurifying;
    public final CachedLongValue SupremePurifying;
    public final CachedLongValue CosmicPurifying;
    public final CachedLongValue InfinitePurifying;
    public final CachedLongValue AbsoluteCentrifugingInput;
    public final CachedLongValue SupremeCentrifugingInput;
    public final CachedLongValue CosmicCentrifugingInput;
    public final CachedLongValue InfiniteCentrifugingInput;
    public final CachedLongValue AbsoluteCentrifugingOutput;
    public final CachedLongValue SupremeCentrifugingOutput;
    public final CachedLongValue CosmicCentrifugingOutput;
    public final CachedLongValue InfiniteCentrifugingOutput;
    public final CachedLongValue AbsoluteWashingInput;
    public final CachedLongValue SupremeWashingInput;
    public final CachedLongValue CosmicWashingInput;
    public final CachedLongValue InfiniteWashingInput;
    public final CachedIntValue AbsoluteWashingFluidInput;
    public final CachedIntValue SupremeWashingFluidInput;
    public final CachedIntValue CosmicWashingFluidInput;
    public final CachedIntValue InfiniteWashingFluidInput;
    public final CachedLongValue AbsoluteWashingOutput;
    public final CachedLongValue SupremeWashingOutput;
    public final CachedLongValue CosmicWashingOutput;
    public final CachedLongValue InfiniteWashingOutput;
    public final CachedLongValue AbsoluteDissolvingInput;
    public final CachedLongValue SupremeDissolvingInput;
    public final CachedLongValue CosmicDissolvingInput;
    public final CachedLongValue InfiniteDissolvingInput;
    public final CachedLongValue AbsoluteDissolvingOutput;
    public final CachedLongValue SupremeDissolvingOutput;
    public final CachedLongValue CosmicDissolvingOutput;
    public final CachedLongValue InfiniteDissolvingOutput;
    public final CachedLongValue AbsoluteOxidizing;
    public final CachedLongValue SupremeOxidizing;
    public final CachedLongValue CosmicOxidizing;
    public final CachedLongValue InfiniteOxidizing;
    public final CachedLongValue AbsolutePigmentExtracting;
    public final CachedLongValue SupremePigmentExtracting;
    public final CachedLongValue CosmicPigmentExtracting;
    public final CachedLongValue InfinitePigmentExtracting;
    public final CachedIntValue AbsoluteLiquifying;
    public final CachedIntValue SupremeLiquifying;
    public final CachedIntValue CosmicLiquifying;
    public final CachedIntValue InfiniteLiquifying;
    public final CachedLongValue AbsolutePainting;
    public final CachedLongValue SupremePainting;
    public final CachedLongValue CosmicPainting;
    public final CachedLongValue InfinitePainting;
    public final CachedLongValue AbsolutePlanting;
    public final CachedLongValue SupremePlanting;
    public final CachedLongValue CosmicPlanting;
    public final CachedLongValue InfinitePlanting;
    public final CachedLongValue AbsolutePRCInput;
    public final CachedLongValue SupremePRCInput;
    public final CachedLongValue CosmicPRCInput;
    public final CachedLongValue InfinitePRCInput;
    public final CachedIntValue AbsolutePRCFluidInput;
    public final CachedIntValue SupremePRCFluidInput;
    public final CachedIntValue CosmicPRCFluidInput;
    public final CachedIntValue InfinitePRCFluidInput;
    public final CachedLongValue AbsolutePRCOutput;
    public final CachedLongValue SupremePRCOutput;
    public final CachedLongValue CosmicPRCOutput;
    public final CachedLongValue InfinitePRCOutput;
    public final CachedLongValue AbsoluteReplicating;
    public final CachedLongValue SupremeReplicating;
    public final CachedLongValue CosmicReplicating;
    public final CachedLongValue InfiniteReplicating;
    public final CachedIntValue AdvancedElectricPump;

    public MMCMekExtrasMachineConfig() {
        ForgeConfigSpec.Builder builder = new ForgeConfigSpec.Builder();
        builder.comment("Adjustment of the capacity of the machine's internal tank");
        builder.push("Mekanism_Extras").push("ExtrasCompressing");
        AbsoluteCompressing = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 2541000, Vanilla: 25410").defineInRange("absoluteChemicalTankCapacity", 2541000, 1, Long.MAX_VALUE));
        SupremeCompressing  = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 3549000, Vanilla: 35490").defineInRange("supremeChemicalTankCapacity", 3549000, 1, Long.MAX_VALUE));
        CosmicCompressing   = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB) Default: 4725000, Vanilla: 47250").defineInRange("cosmicChemicalTankCapacity", 4725000, 1, Long.MAX_VALUE));
        InfiniteCompressing = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 6069000, Vanilla: 60690").defineInRange("infiniteChemicalTankCapacity", 6069000, 1, Long.MAX_VALUE));
        builder.pop().push("ExtrasInjecting");
        AbsoluteInjecting = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 2541000, Vanilla: 25410").defineInRange("absoluteChemicalTankCapacity", 2541000, 1, Long.MAX_VALUE));
        SupremeInjecting  = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 3549000, Vanilla: 35490").defineInRange("supremeChemicalTankCapacity", 3549000, 1, Long.MAX_VALUE));
        CosmicInjecting   = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB) Default: 4725000, Vanilla: 47250").defineInRange("cosmicChemicalTankCapacity", 4725000, 1, Long.MAX_VALUE));
        InfiniteInjecting = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 6069000, Vanilla: 60690").defineInRange("infiniteChemicalTankCapacity", 6069000, 1, Long.MAX_VALUE));
        builder.pop().push("ExtrasPurifying");
        AbsolutePurifying = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 2541000, Vanilla: 25410").defineInRange("absoluteChemicalTankCapacity", 2541000, 1, Long.MAX_VALUE));
        SupremePurifying  = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 3549000, Vanilla: 35490").defineInRange("supremeChemicalTankCapacity", 3549000, 1, Long.MAX_VALUE));
        CosmicPurifying   = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB) Default: 4725000, Vanilla: 47250").defineInRange("cosmicChemicalTankCapacity", 4725000, 1, Long.MAX_VALUE));
        InfinitePurifying = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 6069000, Vanilla: 60690").defineInRange("infiniteChemicalTankCapacity", 6069000, 1, Long.MAX_VALUE));
        builder.pop().push("ExtrasInfusingFactory");
        AbsoluteMetallurgicInfuserFactory = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 12100000, Vanilla: 121000").defineInRange("absoluteChemicalTankCapacity", 12100000, 1, Long.MAX_VALUE));
        SupremeMetallurgicInfuserFactory = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 16900000, Vanilla: 169000").defineInRange("supremeChemicalTankCapacity", 16900000, 1, Long.MAX_VALUE));
        CosmicMetallurgicInfuserFactory = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 22500000, Vanilla: 225000").defineInRange("cosmicChemicalTankCapacity", 22500000, 1, Long.MAX_VALUE));
        InfiniteMetallurgicInfuserFactory = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 28900000, Vanilla: 289000").defineInRange("infiniteChemicalTankCapacity", 28900000, 1, Long.MAX_VALUE));
        builder.pop().push("CentrifugingFactoryExtras");
        AbsoluteCentrifugingInput    = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 11000000, Vanilla: 110000").defineInRange("absoluteInputChemicalTankCapacity", 11000000, 1, Long.MAX_VALUE));
        SupremeCentrifugingInput     = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 13000000, Vanilla: 130000").defineInRange("supremeInputChemicalTankCapacity", 13000000, 1, Long.MAX_VALUE));
        CosmicCentrifugingInput      = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 15000000, Vanilla: 150000").defineInRange("cosmicInputChemicalTankCapacity", 15000000, 1, Long.MAX_VALUE));
        InfiniteCentrifugingInput    = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 17000000, Vanilla: 170000").defineInRange("infiniteInputChemicalTankCapacity", 17000000, 1, Long.MAX_VALUE));
        AbsoluteCentrifugingOutput    = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 11000000, Vanilla: 110000").defineInRange("absoluteOutputChemicalTankCapacity", 11000000, 1, Long.MAX_VALUE));
        SupremeCentrifugingOutput     = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 13000000, Vanilla: 130000").defineInRange("supremeOutputChemicalTankCapacity", 13000000, 1, Long.MAX_VALUE));
        CosmicCentrifugingOutput      = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 15000000, Vanilla: 150000").defineInRange("cosmicOutputChemicalTankCapacity", 15000000, 1, Long.MAX_VALUE));
        InfiniteCentrifugingOutput    = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 17000000, Vanilla: 170000").defineInRange("infiniteOutputChemicalTankCapacity", 17000000, 1, Long.MAX_VALUE));
        builder.pop().push("WashingFactoryExtras");
        AbsoluteWashingInput     = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 11000000, Vanilla: 110000").defineInRange("absoluteInputChemicalTankCapacity", 11000000, 1, Long.MAX_VALUE));
        SupremeWashingInput      = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 13000000, Vanilla: 130000").defineInRange("supremeInputChemicalTankCapacity", 13000000, 1, Long.MAX_VALUE));
        CosmicWashingInput       = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 15000000, Vanilla: 150000").defineInRange("cosmicInputChemicalTankCapacity", 15000000, 1, Long.MAX_VALUE));
        InfiniteWashingInput     = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 17000000, Vanilla: 170000").defineInRange("infiniteInputChemicalTankCapacity", 17000000, 1, Long.MAX_VALUE));
        AbsoluteWashingFluidInput   = CachedIntValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 11000000, Vanilla: 110000").defineInRange("absoluteInputFluidTankCapacity", 11000000, 1, Integer.MAX_VALUE));
        SupremeWashingFluidInput    = CachedIntValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 13000000, Vanilla: 130000").defineInRange("supremeInputFluidTankCapacity", 13000000, 1, Integer.MAX_VALUE));
        CosmicWashingFluidInput     = CachedIntValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 15000000, Vanilla: 150000").defineInRange("cosmicInputFluidTankCapacity", 15000000, 1, Integer.MAX_VALUE));
        InfiniteWashingFluidInput   = CachedIntValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 17000000, Vanilla: 170000").defineInRange("infiniteInputFluidTankCapacity", 17000000, 1, Integer.MAX_VALUE));
        AbsoluteWashingOutput     = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 11000000, Vanilla: 110000").defineInRange("absoluteOutputChemicalTankCapacity", 11000000, 1, Long.MAX_VALUE));
        SupremeWashingOutput      = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 13000000, Vanilla: 130000").defineInRange("supremeOutputChemicalTankCapacity", 13000000, 1, Long.MAX_VALUE));
        CosmicWashingOutput       = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 15000000, Vanilla: 150000").defineInRange("cosmicOutputChemicalTankCapacity", 15000000, 1, Long.MAX_VALUE));
        InfiniteWashingOutput     = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 17000000, Vanilla: 170000").defineInRange("infiniteOutputChemicalTankCapacity", 17000000, 1, Long.MAX_VALUE));
        builder.pop().push("DissolvingFactoryExtras");
        AbsoluteDissolvingInput     = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 11000000, Vanilla: 110000").defineInRange("absoluteInputChemicalTankCapacity", 11000000, 1, Long.MAX_VALUE));
        SupremeDissolvingInput      = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 13000000, Vanilla: 130000").defineInRange("supremeInputChemicalTankCapacity", 13000000, 1, Long.MAX_VALUE));
        CosmicDissolvingInput       = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 15000000, Vanilla: 150000").defineInRange("cosmicInputChemicalTankCapacity", 15000000, 1, Long.MAX_VALUE));
        InfiniteDissolvingInput     = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 17000000, Vanilla: 170000").defineInRange("infiniteInputChemicalTankCapacity", 17000000, 1, Long.MAX_VALUE));
        AbsoluteDissolvingOutput    = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 11000000, Vanilla: 110000").defineInRange("absoluteOutputChemicalTankCapacity", 11000000, 1, Long.MAX_VALUE));
        SupremeDissolvingOutput     = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 13000000, Vanilla: 130000").defineInRange("supremeOutputChemicalTankCapacity", 13000000, 1, Long.MAX_VALUE));
        CosmicDissolvingOutput      = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 15000000, Vanilla: 150000").defineInRange("cosmicOutputChemicalTankCapacity", 15000000, 1, Long.MAX_VALUE));
        InfiniteDissolvingOutput    = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 17000000, Vanilla: 170000").defineInRange("infiniteOutputChemicalTankCapacity", 17000000, 1, Long.MAX_VALUE));
        builder.pop().push("OxidizingFactoryExtras");
        AbsoluteOxidizing       = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 11000000, Vanilla: 110000").defineInRange("absoluteChemicalTankCapacity", 11000000, 1, Long.MAX_VALUE));
        SupremeOxidizing        = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 13000000, Vanilla: 130000").defineInRange("supremeChemicalTankCapacity", 13000000, 1, Long.MAX_VALUE));
        CosmicOxidizing         = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 15000000, Vanilla: 150000").defineInRange("cosmicChemicalTankCapacity", 15000000, 1, Long.MAX_VALUE));
        InfiniteOxidizing       = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 17000000, Vanilla: 170000").defineInRange("infiniteChemicalTankCapacity", 17000000, 1, Long.MAX_VALUE));
        builder.pop().push("PigmentExtractingFactoryExtras");
        AbsolutePigmentExtracting   = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 11000000, Vanilla: 110000").defineInRange("absoluteChemicalTankCapacity", 11000000, 1, Long.MAX_VALUE));
        SupremePigmentExtracting    = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 13000000, Vanilla: 130000").defineInRange("supremeChemicalTankCapacity", 13000000, 1, Long.MAX_VALUE));
        CosmicPigmentExtracting     = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 15000000, Vanilla: 150000").defineInRange("cosmicChemicalTankCapacity", 15000000, 1, Long.MAX_VALUE));
        InfinitePigmentExtracting   = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 17000000, Vanilla: 170000").defineInRange("infiniteChemicalTankCapacity", 17000000, 1, Long.MAX_VALUE));
        builder.pop().push("LiquifyingFactoryExtras");
        AbsoluteLiquifying  = CachedIntValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 11000000, Vanilla: 110000").defineInRange("absoluteFluidTankCapacity", 11000000, 1, Integer.MAX_VALUE));
        SupremeLiquifying   = CachedIntValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 13000000, Vanilla: 130000").defineInRange("supremeFluidTankCapacity", 13000000, 1, Integer.MAX_VALUE));
        CosmicLiquifying    = CachedIntValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 15000000, Vanilla: 150000").defineInRange("cosmicFluidTankCapacity", 15000000, 1, Integer.MAX_VALUE));
        InfiniteLiquifying  = CachedIntValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 17000000, Vanilla: 170000").defineInRange("infiniteFluidTankCapacity", 17000000, 1, Integer.MAX_VALUE));
        builder.pop().push("PaintingFactoryExtras");
        AbsolutePainting    = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 11000000, Vanilla: 110000").defineInRange("absoluteChemicalTankCapacity", 11000000, 1, Long.MAX_VALUE));
        SupremePainting     = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 13000000, Vanilla: 130000").defineInRange("supremeChemicalTankCapacity", 13000000, 1, Long.MAX_VALUE));
        CosmicPainting      = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 15000000, Vanilla: 150000").defineInRange("cosmicChemicalTankCapacity", 15000000, 1, Long.MAX_VALUE));
        InfinitePainting    = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 17000000, Vanilla: 170000").defineInRange("infiniteChemicalTankCapacity", 17000000, 1, Long.MAX_VALUE));
        builder.pop().push("PlantingFactoryExtras");
        AbsolutePlanting    = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 11000000, Vanilla: 110000").defineInRange("absoluteChemicalTankCapacity", 11000000, 1, Long.MAX_VALUE));
        SupremePlanting     = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 13000000, Vanilla: 130000").defineInRange("supremeChemicalTankCapacity", 13000000, 1, Long.MAX_VALUE));
        CosmicPlanting      = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 15000000, Vanilla: 150000").defineInRange("cosmicChemicalTankCapacity", 15000000, 1, Long.MAX_VALUE));
        InfinitePlanting    = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 17000000, Vanilla: 170000").defineInRange("infiniteChemicalTankCapacity", 17000000, 1, Long.MAX_VALUE));
        builder.pop().push("PRCFactoryExtras");
        AbsolutePRCInput        = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 11000000, Vanilla: 110000").defineInRange("absoluteInputChemicalTankCapacity", 11000000, 1, Long.MAX_VALUE));
        SupremePRCInput         = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 13000000, Vanilla: 130000").defineInRange("supremeInputChemicalTankCapacity", 13000000, 1, Long.MAX_VALUE));
        CosmicPRCInput          = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 15000000, Vanilla: 150000").defineInRange("cosmicInputChemicalTankCapacity", 15000000, 1, Long.MAX_VALUE));
        InfinitePRCInput        = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 17000000, Vanilla: 170000").defineInRange("infiniteInputChemicalTankCapacity", 17000000, 1, Long.MAX_VALUE));
        AbsolutePRCFluidInput   = CachedIntValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 11000000, Vanilla: 110000").defineInRange("absoluteInputFluidTankCapacity", 11000000, 1, Integer.MAX_VALUE));
        SupremePRCFluidInput    = CachedIntValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 13000000, Vanilla: 130000").defineInRange("supremeInputFluidTankCapacity", 13000000, 1, Integer.MAX_VALUE));
        CosmicPRCFluidInput     = CachedIntValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 15000000, Vanilla: 150000").defineInRange("cosmicInputFluidTankCapacity", 15000000, 1, Integer.MAX_VALUE));
        InfinitePRCFluidInput   = CachedIntValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 17000000, Vanilla: 170000").defineInRange("infiniteInputFluidTankCapacity", 17000000, 1, Integer.MAX_VALUE));
        AbsolutePRCOutput       = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 11000000, Vanilla: 110000").defineInRange("absoluteOutputChemicalTankCapacity", 11000000, 1, Long.MAX_VALUE));
        SupremePRCOutput        = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 13000000, Vanilla: 130000").defineInRange("supremeOutputChemicalTankCapacity", 13000000, 1, Long.MAX_VALUE));
        CosmicPRCOutput         = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 15000000, Vanilla: 150000").defineInRange("cosmicOutputChemicalTankCapacity", 15000000, 1, Long.MAX_VALUE));
        InfinitePRCOutput       = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 17000000, Vanilla: 170000").defineInRange("infiniteOutputChemicalTankCapacity", 17000000, 1, Long.MAX_VALUE));
        builder.pop().push("ReplicatingFactoryExtras");
        AbsoluteReplicating     = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 11000000, Vanilla: 110000").defineInRange("absoluteChemicalTankCapacity", 11000000, 1, Long.MAX_VALUE));
        SupremeReplicating      = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 13000000, Vanilla: 130000").defineInRange("supremeChemicalTankCapacity", 13000000, 1, Long.MAX_VALUE));
        CosmicReplicating       = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 15000000, Vanilla: 150000").defineInRange("cosmicChemicalTankCapacity", 15000000, 1, Long.MAX_VALUE));
        InfiniteReplicating     = CachedLongValue.wrap(this, builder.comment("Chemical tank capacity (mB). Default: 17000000, Vanilla: 170000").defineInRange("infiniteChemicalTankCapacity", 17000000, 1, Long.MAX_VALUE));
        builder.pop().push("AdvancedElectricPump");
        AdvancedElectricPump = CachedIntValue.wrap(this, builder.comment("Fluid tank capacity (mB). Default: 1000000000, Vanilla: 10000000").defineInRange("fluidTankCapacity", 1000000000, 1, Integer.MAX_VALUE));
        builder.pop().pop();
        configSpec = builder.build();
    }

    @Override
    public String getFileName() {
        return "MMCMekExtrasMachine";
    }

    @Override
    public ForgeConfigSpec getConfigSpec() {
        return configSpec;
    }

    @Override
    public ModConfig.Type getConfigType() {
        return ModConfig.Type.SERVER;
    }
}
